-- MySQL Script generated by MySQL Workbench
-- Sat Mar 21 20:07:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RedeSocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RedeSocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RedeSocial` DEFAULT CHARACTER SET utf8 ;
USE `RedeSocial` ;

-- -----------------------------------------------------
-- Table `RedeSocial`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedeSocial`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `bio` VARCHAR(255) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT  CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT  CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedeSocial`.` posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedeSocial`.` posts` (
  `idposts` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `visibility` ENUM('public', 'private') NOT NULL DEFAULT 'public',
  `created_at` DATETIME NULL,
  ` updated_at` DATETIME NULL,
  INDEX `FK_POSTS_USER_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`idposts`),
  CONSTRAINT `FK_POSTS_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `RedeSocial`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedeSocial`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedeSocial`.`comments` (
  `idcomments` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL,
  `user_id` INT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`idcomments`),
  INDEX `FK_COMMENTS_POSTS_idx` (`post_id` ASC) VISIBLE,
  INDEX `FK_COMMENTS_USERS_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_COMMENTS_POSTS`
    FOREIGN KEY (`post_id`)
    REFERENCES `RedeSocial`.` posts` (`idposts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COMMENTS_USERS`
    FOREIGN KEY (`user_id`)
    REFERENCES `RedeSocial`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedeSocial`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedeSocial`.`likes` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`user_id`, `post_id`),
  INDEX `FK_LIKES_POSTS_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `FK_LIKES_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `RedeSocial`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LIKES_POSTS`
    FOREIGN KEY (`post_id`)
    REFERENCES `RedeSocial`.` posts` (`idposts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RedeSocial`.` audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RedeSocial`.` audit_log` (
  `id audit_log` BIGINT NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(64) NULL,
  ` operation` ENUM('INSERT', 'UPDATE', 'DELETE') NULL,
  `record_id` BIGINT NULL,
  ` changed_by_user_id` INT NOT NULL,
  `details` TEXT NULL,
  ` created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id audit_log`))
ENGINE = InnoDB;

USE `RedeSocial` ;

-- -----------------------------------------------------
-- function sf_user_create
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sf_user_create`(
`pn_name` varchar(120),
`pn_email` varchar(160),
`pn_bio` varchar(255),
`pn_password_hash` varchar(255)
) returns int(1)
BEGIN
    insert into users(name, email, bio, password_hash)
			values(pn_name, pn_email, pn_bio, pn_password_hash);
return 0; 
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- function sf_user_update
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sf_user_update` (
  pn_id INT,
  pn_name VARCHAR(120),
  pn_email VARCHAR(160),
  pn_bio VARCHAR(255),
  pn_password_hash VARCHAR(255)
) RETURNS INT(1)
BEGIN
  UPDATE users
  SET
    name = pn_name,
    email = pn_email,
    bio = pn_bio,
    password_hash = pn_password_hash,
    updated_at = NOW()
  WHERE idusers = pn_id;

  RETURN 0;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function sf_user_delete
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
create function `sf_user_delete`(
`pn_id` INT
) returns int(1)
begin 
    delete from users where idusers = pn_id;
return 0; 
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- function sp_post_create
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sp_post_create` (
`pn_user-id` INT, 
`pn_content` TEXT,
`pn_visibility` ENUM('public', 'private')
) returns int(1)
BEGIN
 insert into posts (user_id, content, visibility)
			values(pn_user_id, pn_content, pn_visibility); 
return 0;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function sf_posts_update
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sf_posts_update` (
  pn_posts_id INT,
  pn_content VARCHAR(120),
  pn_visibility VARCHAR(160)
) RETURNS INT(1)
BEGIN
  UPDATE posts
  SET
    user_id = pn_user_id,
    content = pn_content,
    visibility = pn_visibility,
    updated_at = NOW()
  WHERE idposts = pn_posts_id;

  RETURN 0;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function sf_post_delete
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sf_post_delete`(
`pn_id` INT
) returns int(1)
begin 
    delete from posts where idposts = pn_id;
return 0; 
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- function sp_comment_create
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sp_comment_create` (
`pn_post_id` INT,
`pn_user_id` INT,
`pn_content` TEXT
) returns int(1)
BEGIN
 insert into comments(post_id, user_id, content)
			values(pn_post_id, pn_user_id, pn_content);
return 0;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function sp_comment_delete
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sp_comment_delete` (
`pn_id` INT
) returns int(1)
BEGIN
	delete from comments where idcomments = pn_id;
return 0;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function sp_like_add
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sp_like_add` (
`pn_user_id` INT, 
`pn_post_id` INT
) returns int(1)
BEGIN
insert into likes(user_id, post_id)
			values(pn_user_id, pn_post_id);
return 0;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- function sp_like_remove
-- -----------------------------------------------------

DELIMITER $$
USE `RedeSocial`$$
CREATE FUNCTION `sp_like_remove` (
`pn_user_id` INT,
`pn_post_id` INT
) returns int(1)
BEGIN
	delete from likes where user_id = pn_user_id and post_id = pn_post_id;
return 0;
END;$$

DELIMITER ;
USE `RedeSocial`;

DELIMITER $$
USE `RedeSocial`$$
CREATE DEFINER = CURRENT_USER TRIGGER `RedeSocial`.`users_BEFORE_INSERT` BEFORE INSERT ON `users` FOR EACH ROW
BEGIN
declare msg varchar(255);
declare email int;

select count(email) into email from users where email = new.email;
if new.email is null or new.email = "" then
set msg = 'o campo email é de preenchimento obrigatório';
signal sqlstate'45000' set message_text = msg;
end if;

if email >= 1 then
set msg ='já existe um usuário com esse email';
signal sqlstate'45000' set message_text = msg;
end if;
END$$

USE `RedeSocial`$$
CREATE DEFINER = CURRENT_USER TRIGGER `RedeSocial`.`users_BEFORE_UPDATE` BEFORE UPDATE ON `users` FOR EACH ROW
BEGIN
declare msg varchar(255);
if new.email is null or new.email = '' then
    set msg = 'O campo "Email" não pode ser vazio!';
    signal sqlstate '45000' set message_text = msg;
end if;

if (select count(*) from users where email = new.email and email <> old.email) > 0 then
    set msg = 'Erro: Este email já está cadastrado!';
    signal sqlstate '45000' set message_text = msg;
end if;
END$$

USE `RedeSocial`$$
CREATE DEFINER = CURRENT_USER TRIGGER `RedeSocial`.` posts_BEFORE_INSERT` BEFORE INSERT ON ` posts` FOR EACH ROW
BEGIN
declare msg varchar(255);

 if new.content is null or char_length(trim(new.content)) < 5 then
 signal sqlstate '45000'
 set message_text = 'Conteúdo do post deve ter pelo menos 5 caracteres não vazios.';
 end if;

END$$

USE `RedeSocial`$$
CREATE DEFINER = CURRENT_USER TRIGGER `RedeSocial`.`comments_BEFORE_INSERT` BEFORE INSERT ON `comments` FOR EACH ROW
BEGIN
declare msg varchar(255);

if new.content is null or new.content = '' then
signal sqlstate '45000'
set message_text='Não pode haver comentários em branco';
end if;
END$$

USE `RedeSocial`$$
CREATE DEFINER = CURRENT_USER TRIGGER `RedeSocial`.`likes_BEFORE_INSERT` BEFORE INSERT ON `likes` FOR EACH ROW
BEGIN
    DECLARE msg VARCHAR(255);
    DECLARE like_existe INT;

     SELECT COUNT(*) INTO like_existe 
    FROM `likes` 
    WHERE user_id = NEW.user_id AND post_id = NEW.post_id;

    IF like_existe >= 0 THEN 
    delete from likes where user_id = NEW.user_id AND post_id = NEW.post_id;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
